module.exports = BlendMode =

  NORMAL: 'normal'
  BLEND: 'blend'
  ADD: 'add'
  SUBTRACT: 'subtract'
  DARKEST: 'darkest'
  LIGHTEST: 'lightest'
  DIFFERENCE: 'difference'
  EXCLUSION: 'exclusion'
  MULTIPLY: 'multiply'
  SCREEN: 'screen'

  OVERLAY: 'overlay'
  SOFT_LIGHT: 'softLight'
  HARD_LIGHT: 'hardLight'
  VIVID_LIGHT: 'vividLight'
  LINEAR_LIGHT: 'linearLight'
  PIN_LIGHT: 'pinLight'
  HARD_MIX: 'hardMix'

  DODGE: 'dodge'
  BURN: 'burn'
  LINEAR_DODGE: 'linearDodge'
  LINEAR_BURN: 'linearBurn'
